import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
      <title>Vendas App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.icon" />
      </Head>
      <h1>TESTE DEV</h1>
    </div>
  )
}